// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykardcgknnoepacpdqve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrYXJkY2drbm5vZXBhY3BkcXZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MDE5MDMsImV4cCI6MjA2MzE3NzkwM30.CJ0ilftbVRmXs8y6zOWCwtdKXHGLZEaeqdvNrgH8gDw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);